#!/bin/bash

WALLPAPER=mow
CODENAME_SAFE=mow
DESCRIPTION=mow
VERSION=2022.1.0
DISTRIBUTION=unstable

# Gdm3 and Gnome settings
BACKGROUND_RENDERING_OPTION="stretched"


# FLL_LIVE_USER for 10-live-cd.pkla
FLL_LIVE_USER=siducer
