#!/bin/bash

WALLPAPER=big-crime
CODENAME_SAFE=big-crime
DESCRIPTION=lightdm theme for Big Crime
VERSION=2026.1
DISTRIBUTION=unstable

# Gdm3 and Gnome settings
BACKGROUND_RENDERING_OPTION="stretched"


# FLL_LIVE_USER for 10-live-cd.pkla
FLL_LIVE_USER=siducer
