#!/bin/bash

WALLPAPER=farewell
CODENAME_SAFE=farewell
DESCRIPTION=farewell
VERSION=2021.2.0
DISTRIBUTION=unstable

# Gdm3 and Gnome settings
BACKGROUND_RENDERING_OPTION="stretched"


# FLL_LIVE_USER for 10-live-cd.pkla
FLL_LIVE_USER=siducer
